-- Topic queue for AI-generated blog posts
-- Each row is one prepared topic that the weekly generator can pick up.

CREATE TABLE IF NOT EXISTS public.blog_topic_queue (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  topic_title TEXT NOT NULL,
  keywords TEXT[] NOT NULL DEFAULT '{}',
  image_query TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  used BOOLEAN NOT NULL DEFAULT FALSE,
  used_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.blog_topic_queue ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins can do everything with topic queue"
  ON public.blog_topic_queue FOR ALL
  USING (public.has_role(auth.uid(), 'admin'))
  WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE INDEX IF NOT EXISTS idx_blog_topic_queue_used
  ON public.blog_topic_queue(used, sort_order);

-- Seed with ~30 Croatian topics about napuhanci (bouncy castles), dječje proslave
-- Each topic includes target keywords and a Pexels image query (in English for better results).
INSERT INTO public.blog_topic_queue (sort_order, topic_title, keywords, image_query) VALUES
  (10, 'Kako organizirati savršen dječji rođendan na otvorenom',
    ARRAY['dječji rođendan na otvorenom', 'organizacija rođendana', 'rođendan u dvorištu'],
    'kids birthday party outdoor'),
  (20, 'Najam napuhanca u Zagrebu - cijene, dostava i sve što trebate znati',
    ARRAY['najam napuhanca Zagreb', 'iznajmljivanje napuhanaca', 'cijene napuhanaca'],
    'bouncy castle inflatable'),
  (30, '10 ideja za temu dječjeg rođendana koje će oduševiti mališane',
    ARRAY['teme dječjih rođendana', 'ideje za rođendan', 'dječje proslave'],
    'children birthday decoration'),
  (40, 'Sigurnost djece na napuhancima - vodič za roditelje',
    ARRAY['sigurnost na napuhancima', 'sigurnost djece', 'pravila napuhanca'],
    'children playing safe'),
  (50, 'Kako odabrati pravi napuhanac za dob i broj djece',
    ARRAY['odabir napuhanca', 'napuhanac za uzrast', 'koji napuhanac odabrati'],
    'inflatable bounce house'),
  (60, '5 razloga zašto je napuhanac najbolja zabava za dječji rođendan',
    ARRAY['zabava za rođendan', 'napuhanac za rođendan', 'najbolja dječja zabava'],
    'children jumping fun'),
  (70, 'Dječji rođendan kod kuće - praktični vodič od A do Ž',
    ARRAY['rođendan kod kuće', 'organizacija dječje proslave', 'rođendan u stanu'],
    'birthday cake home'),
  (80, 'Najpopularnije teme dječjih rođendana - što djeca vole 2026.',
    ARRAY['popularne teme rođendana', 'trendovi dječjih rođendana', 'rođendan tema'],
    'kids party decoration'),
  (90, 'Kako pripremiti dvorište za dječji rođendan i napuhanac',
    ARRAY['priprema dvorišta', 'rođendan u dvorištu', 'napuhanac u dvorištu'],
    'garden party kids'),
  (100, 'Što sve treba za nezaboravni dječji rođendan u Zagrebu',
    ARRAY['dječji rođendan Zagreb', 'rođendan u Zagrebu', 'proslava Zagreb'],
    'birthday party celebration'),
  (110, 'Kreativne aktivnosti za dječji rođendan uz napuhanac',
    ARRAY['aktivnosti za rođendan', 'igre na rođendanu', 'zabava za djecu'],
    'kids activities playing'),
  (120, 'Vodič za roditelje: koliko dugo iznajmiti napuhanac',
    ARRAY['trajanje najma', 'koliko iznajmiti napuhanac', 'najam po satu'],
    'children playing time'),
  (130, 'Rođendan za jednogodišnjaka - ideje koje će oduševiti',
    ARRAY['prvi rođendan', 'rođendan jednogodišnjaka', 'rođendan male djece'],
    'first birthday baby'),
  (140, 'Dvorište bez trave? Ovako možete postaviti napuhanac na betonu',
    ARRAY['napuhanac na betonu', 'postavljanje napuhanca', 'napuhanac bez trave'],
    'backyard concrete patio'),
  (150, 'Najam pivskog stola i klupa za vašu proslavu',
    ARRAY['pivski stolovi', 'najam stolova', 'oprema za proslavu'],
    'outdoor wooden tables'),
  (160, 'Kako organizirati rođendan u parku ili na livadi',
    ARRAY['rođendan u parku', 'proslava na livadi', 'rođendan vani'],
    'park picnic children'),
  (170, 'Što ako pada kiša? Plan B za dječji rođendan na otvorenom',
    ARRAY['rođendan po kiši', 'plan B za rođendan', 'rođendan u zatvorenom'],
    'rainy day kids indoor'),
  (180, 'Najbolji napuhanci za djevojčice - jednorog, princeze i drugi',
    ARRAY['napuhanac jednorog', 'napuhanac za djevojčice', 'princeze napuhanac'],
    'pink unicorn toy'),
  (190, 'Napuhanci za dječake - Minecraft, dinosauri i Paw Patrol',
    ARRAY['napuhanac Minecraft', 'napuhanac dinosauri', 'napuhanac Paw Patrol'],
    'dinosaur toy kids'),
  (200, 'Koliko košta organizacija dječjeg rođendana - realan budžet',
    ARRAY['cijena rođendana', 'budžet za proslavu', 'troškovi rođendana'],
    'birthday party planning'),
  (210, 'Hrana i piće za dječji rođendan - jednostavni i zdravi prijedlozi',
    ARRAY['hrana za rođendan', 'meni za rođendan', 'zdrave užine'],
    'kids healthy snacks'),
  (220, 'Pokloni za goste na dječjem rođendanu - 15 sjajnih ideja',
    ARRAY['pokloni za goste', 'party favori', 'darovi na rođendanu'],
    'party gift bag'),
  (230, 'Rođendanska torta - kupiti gotovu ili napraviti doma?',
    ARRAY['rođendanska torta', 'tema torte', 'torta za rođendan'],
    'birthday cake colorful'),
  (240, 'Foto kutak na dječjem rođendanu - kako napraviti zabavnu pozadinu',
    ARRAY['foto kutak', 'photo booth rođendan', 'foto pozadina'],
    'photo booth backdrop'),
  (250, 'Pozivnice za dječji rođendan - kreativne ideje i besplatni predlošci',
    ARRAY['pozivnice za rođendan', 'kreativne pozivnice', 'predlošci pozivnica'],
    'invitation card design'),
  (260, 'Dječji rođendan u 3 koraka - planiranje za zauzete roditelje',
    ARRAY['brza organizacija', 'planiranje rođendana', 'rođendan u kratkom roku'],
    'family planning event'),
  (270, 'Animatori na dječjem rođendanu - vrijedi li?',
    ARRAY['animatori za djecu', 'animatori rođendan', 'zabava s animatorima'],
    'children entertainment'),
  (280, 'Najčešće greške pri organizaciji dječjeg rođendana i kako ih izbjeći',
    ARRAY['greške na rođendanu', 'kako izbjeći probleme', 'savjeti za rođendan'],
    'birthday party tips'),
  (290, 'Rođendan blizanaca - kako organizirati zabavu za dvoje',
    ARRAY['rođendan blizanaca', 'dvostruka proslava', 'rođendan za dvoje'],
    'twins birthday party'),
  (300, 'Zimska proslava dječjeg rođendana - ideje kad nema dvorišta',
    ARRAY['zimski rođendan', 'rođendan u prosincu', 'rođendan zimi'],
    'winter party indoor');
