// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egwtrsfcobwybcnbqsok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnd3Ryc2Zjb2J3eWJjbmJxc29rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NTQxNjYsImV4cCI6MjA3NDQzMDE2Nn0.MArJbgzxXgc4Pq18ZlXpN5zJieso-eQtNnWw4hPCjwc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});